dist: trusty
sudo: required
language: python
cache:
  directories:
  - $HOME/.pyembedpg
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev xsltproc
install: "pip install -r tests/requirements.txt"
script: py.test -s -v
